/**
 * TypeScript module declaration for the `virtual:content-types` virtual Vite module
 * generated by `frontend/plugins/content-types-plugin.ts`.
 *
 * These types mirror the `ResolvedContentType` interface exported from the plugin.
 */
declare module 'virtual:content-types' {
  export interface ResolvedFrontendImplementation {
    id: string;
    planes: string[];
    delivery: string;
    trust: string;
    priority: number;
    viewer_key: string | null;
    provider_key: string | null;
    bridge: string | null;
    entry: Record<string, unknown> | null;
    capabilities: string[];
    requires_entitlements: string[];
    host_constraints: string[];
  }

  export interface ResolvedContentType {
    /** Stable identifier — from `id` in presentation.json or derived from content type. */
    id: string;
    content_type: string;
    is_wildcard: boolean;
    wildcard_prefix: string | null;
    extensions: string[];
    description: string;
    label: string;
    icon: string;
    color: string;
    badge_class: string;
    tile_class: string;
    modes: string[];
    states: string[];
    default_mode: string;
    default_state: string;
    is_container: boolean;
    creatable: boolean;
    open_action: string | null;
    resource_uri: string | null;
    resource_server: string | null;
    container_variant: string | null;
    viewer: string | null;
    provider: string | null;
    default_depth: number | null;
    max_depth: number | null;
    frontend_version: number | null;
    implementations: ResolvedFrontendImplementation[];
  }

  /** All resolved content types, sorted: exact MIME types first, wildcards last. */
  export const contentTypeDefinitions: ResolvedContentType[];

  /** The ultimate fallback entry used when no type matches. */
  export const CONTENT_TYPE_FALLBACK: ResolvedContentType;
}
